### ISSUE TITLE
Unit testing framework

### ISSUE THREAD

**Issue by mekline** [psych-ds/psychds-validator#2]
At the appropriate moment (soon?), start and/or document a unit testing framework; see BIDS and HED for models. 

Note: MKS is not clear whether these unit tests include, or are separate from, the validation over the reference datasets at https://github.com/bids-standard/bids-examples and https://github.com/hed-standard/hed-examples. Leaving as a single issue for now. 

(Note also: https://github.com/psych-ds/example-datasets currently contains contributed datasets that do not meet the spec, and this is an expected state at this point.  In the future, will need to establish pathways for how people can contribute dataset examples (a) generally and (b) for unit testing.)

**Comment by bleonar5** [comment]
In retrospect, I think it's okay to refer to both of these types of testing as unit tests, with the major dataset testing just being a unit test for the primary "validate" function. 

**I think we can definitely have this testing framework ready for the end of this sprint, including any github action orchestration necessary to trigger testing automatically on PR merges**
