### ISSUE TITLE
CEDAR template for OSF

### ISSUE THREAD

**Issue by bleonar5** [psych-ds/psychds-validator#27]
# TL;DR
COS indicated interest during the followup meeting to M4M in the completion of a polished CEDAR template for psych-DS, to be made available to researchers before the OSF site launches its new CEDAR template integration in late January.

It's already part of our MVP to have this available, but it could be advantageous in terms of visibility for our project to push this out for the OSF's timeline (it should be very, very simple, for what it's worth; I'm not sure that anything more than the minimal test version I mocked up during the conference is necessary at this point)

**Comment by ianchandlercampbell** [comment]
@bleonar5 mentioned today he will have a functional template ready for the meeting on Jan 20th and that it's basically already done!
