### ISSUE TITLE
Integrated documentation desiderata

### ISSUE THREAD

**Issue by mekline** [psych-ds/psychds-validator#3]
A documentation goal for Psych-DS is to mirror the structure between the LinkML machine-readable implementation of the spec, and the (probably readthedocs) human-readable online documentation. 

Ideally, the structurally-organized parts of the human documentation will be implemented via LinkML as well, so that docs can be automatically updated/built as we go!  This would be in addition to other documentation for tutorials, tools & resources, etc. available on the readthedocs site. 

Kay Robbins noted the BIDS progression of development; currently the in-process BIDS validator generates error codes that have neurostars URLs but may not contain the most verbose info about those errors.  HED (also?) maintains more extensive documentation about the error codes at [where?].

**Comment by bleonar5** [comment]
@mekline Do you think this issue would fit better in the psych-ds repo? Since it concerns the schema model and psych-ds spec mostly?
