### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by mekline** [psych-ds/psychds-validator#5]
Everything went fine for me on install, the only bump was this set of instructions:

***
After installing, deno will output some instructions about how to add deno to your PATH variable (so that you can use it without writing out the entire path to the app). It will look like this:

export DENO_INSTALL="/Users/<your_username>/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

If you're unsure how to handle this, you can use these commands to add the lines to the .zshrc file and then source the file so the changes are reloaded: (make sure to modify the command by replacing <your_username> with your actual mac username)

echo -e '\nexport DENO_INSTALL="/Users/<your_username>/.deno"\nexport PATH="$DENO_INSTALL/bin:$PATH"' >> ~/.zshrc
source ~/.zshrc
***

Can the user just copy/paste the first version shown? What's the advantage/disadvantage to the code block that comes next?

**Comment by bleonar5** [comment]
The distinction is that if you run the first set of commands, you will successfully add deno to the PATH, but the change will be undone any time you open a new terminal window. By running the second set of commands, you make it so deno automatically gets added to the path every time you open a terminal window
